kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: web
  labels:
    app: web
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - hosts:
      - {{ .Values.domain }}
    secretName: {{ .Values.secretName }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: 3002
