kind: Deployment
apiVersion: apps/v1
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      containers:
      - name: api
        image: repository/api:{{ .Values.imageTag }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: APP_ENV
          value: {{ .Values.environment }}
        ports:
        - containerPort: 3001
          protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
