kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: api
  labels:
    app: api
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  tls:
  - hosts:
      - {{ .Values.domain }}
    secretName: {{ .Values.secretName }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: api
          servicePort: 3001
